config/routes.rb
Rails.application.routes.draw do
  resources :article_categories
  resources :categories
  resources :users, except: [:new]
  resources :articles
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]
  before_action :require_same_user, only: %i[edit update destroy]

  # GET /articles or /articles.json
  def index
    @articles = Article.paginate(page: params[:page], per_page: 3)
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    # debugger
    @article = Article.new(article_params)
    @article.user = User.find(session[:user_id])
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      redirect_to root_path
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
<div class="container p-5 mb-4 mt-4 bg-light rounded-3">
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="mb-2">
          <%= link_to article.title.capitalize, article_path(article), class: 'text-decoration-none' %>
        </div>
        <div class="mb-4">
          <%= truncate(article.description.capitalize, length: 100) %>
          <div>
            <br>
            <small><strong>Created by:</strong> <%= link_to article.user.username, article.user %> </small>
            <br>
            <small><strong>Last updated:</strong> <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
          <% if article.categories.any? %>
            <small><strong>Categories:</strong> <%= render article.categories %></small>
          <%end %>
        </div>
        <% if logged_in? && (current_user == article.user || current_user.admin?) %>
          <%= link_to 'Edit the article', edit_article_path(article), class:'btn btn-primary' %> 
          <%= link_to 'Destroy the article', article, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, class:"form-label" %>
    <%= form.text_field :title, class: 'form-control', placeholder:"Example input placeholder" %>
  </div>

  <div class="mb-3">
    <%= form.label :description, class:"form-label"%>
    <%= form.text_area :description, class: 'form-control', placeholder:"Example input placeholder"%>
  </div>

  
  <div class="mb-3">
  <%= form.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
    <% cb.label(class: "checkbox-inline input_checkbox me-3") {cb.check_box(class: "checkbox") + ' ' + cb.text} %>
  <% end %>
  </div>

  <div class="actions">
    <%= form.submit class:'btn btn-primary'%>
    <%= link_to 'Back', articles_path, class:'btn btn-success'%>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Articles</h1>
<%= render 'article', obj: @articles %>
<div>
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1>New Article</h1>

<div class="container">
    <%= render 'form', article: @article %>
</div>

app/views/articles/show.html.erb
<div class="p-5 mb-4 mt-4 bg-light rounded-3">
  <h2 class="text-center"><strong>Title:</strong> <%= @article.title.capitalize %></h2>
  <div class="well col-xs-8 col-xs-offset-2 mb-4">
    <h4 class="text-center mt-4"><strong>Description:</strong></h4>
    <hr>
      <%= @article.description.capitalize %>
  </div>
  <% if @article.categories.any? %>
    <p>Categories: <%= render @article.categories %></p>
  <%end %>
  <div class="d-flex bd-highlight mb-3">
    <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
      <%= link_to 'Edit the article', edit_article_path(@article), class:'btn btn-primary p-2 bd-highlight me-1' %> 
      <%= link_to 'Destroy the article', @article, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger p-2 bd-highlight' %>
      <% end %>
  </div>
</div>