config/routes.rb
Rails.application.routes.draw do
  resources :article_categories
  resources :categories
  resources :users, except: [:new]
  resources :articles
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/views/layouts/_footer.html.erb
<footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
    </ul>
    <p class="text-center text-muted">© Reinaldo Márquez</p>
  </footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-secondary bg-gradient">
  <div class="container-fluid">
    <%= link_to "BlogAppRor", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Articles", articles_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Users", users_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Categories", categories_path, class:"nav-link" %>
        </li>
        <% if logged_in? %>
        <li class="nav-item">
          <%= link_to "New article", new_article_path, class:"nav-link" %>
        </li>
        <% end %>
      </ul>
    </ul>
    <% if logged_in? %>
        <%= link_to "Log out", logout_path, method: :delete, class:"d-flex nav-link" %>
        <div class="dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Your profile <%= 'admin' if current_user.admin? %>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to "Edit profile", edit_user_path(current_user), class:"dropdown-item" %></li>
            <li><%= link_to "View profile", user_path(current_user), class:"dropdown-item" %></li>
          </ul>
        </div>
    <% else %>
        <%= link_to "Log in", login_path, class:"d-flex nav-link" %>
        <%= link_to "Sign up", signup_path, class:"d-flex nav-link" %>
    <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

    <title>BlogAppRor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
      <%= yield %>
    </div>    
    <%= render 'layouts/footer' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
  </body>
</html>